### PR TITLE
Add options to configure what clicking on the minimap icon does

### PR DESCRIPTION
**Pull request by conundrum89**
This is complete with DataBroker support, default settings matching the current behaviour, locale updates, and a sensible UI.

I'm open to better ideas on how to specify the available action types - currently they're specified in Config.lua for localisation and creating the dropdown menu, but also checked by hard-coded string value in Windows.lua to determine what action should be run.

### CODE REVIEW

**Comment by Breeni** [comment]
I like the idea, there is 1 change that needs to be done first though. Using openConfig is fine but switching the others toggleWindow:small and toggleWindow:main will allow for adding more windows later especially if support for custom windows is added.

**Comment by conundrum89** [comment]
Thanks, I've made that change (and updated the strings to refer to them as Windows instead of Frames)

**Comment by Breeni** [comment]
Looking good, couple of changes though. SplitAction could just call strsplit(":", actionStr, 2) instead. ActionName should pull the window name from the frameNames table so they are localized, probably needs to be moved up the file though.

**Comment by conundrum89** [comment]
Ah, thanks, I'm pretty new to lua and google didn't turn up the strsplit function!

**Comment by Breeni** [comment]
strsplit is wow only so not surprised it didnt show on google. Wowpedia should have all the custom wow stuff

**Pull request merged**
